server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth_db?createDatabaseIfNotExist=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari: 
      connection-timeout: 30000
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      minimum-idle: 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace